parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  pythonVersion: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      addToPath: true
      architecture: x64
  - template: prepare-general-environment.yml
  - script: |
      python3 -c "import sqlite3; print(f'sqlite3 version={sqlite3.sqlite_version_info}');"
      python3 -m pip install pytest pytest-cov pytest-timeout
      python3 -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=electrumsv --cov-report=xml --cov-report=html electrumsv/tests
    displayName: 'Test with pytest'
  - script: |
      python3 -m pip install mypy
      python3 -m mypy --config-file mypy.ini --python-version ${{ parameters.pythonVersion }}
    displayName: 'Type checking with mypy'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python ${{ parameters.pythonVersion }}'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'